trigger:
- string

resources:
-repo: string

variables:
  dockerFilePath: string
  tags: string

stages:
- stage: string
  displayName: string
  dependsOn: string | string[]
  condition: string
  pool: string | pool
  variables: { string: string } | [variable | variableReference]
  jobs: [job | templateReference]

# Agent jobs
jobs:
- job: string
  pool:
    vmImage: string
  strategy:
    matrix:
      (operating system name):
        containerResource: string
  container: string
  steps:
  - script: string | templateReference

parameters:
- name: string
  displayName: string
  type: string
  default: boolean


# ================================================ Example


trigger
- master

# Using template
extends:
  template: template.yml

pool:
  vmImage: 'ubuntu-16.04'

jobs:
- job: RunInContainer
  strategy:
    matrix:
      ubuntu14:
        containerResource: u14
      ubuntu16:
        containerResource: u16
  container: $[ variables['containerResource'] ]
  steps:
  - script: |
      echo Add other tasks to build, test and deploy
      echo See https://aka.ms/yaml
    displayName: 'Run a multi line script'

  - script: printenv
  - ${{ if (eq(parameters.experimentalTemplate, true)) }}:
    - template: experimental.yml

variables:
  dockerFilePath: '**/Dockerfile'
  tags: '$(Build.BuildId)'

stages:
- stage: A
# Stage B runs if stage A fails
- stage: B
  condition: failed()
# Stage C runs if B succeeded
- stage: C
  condition: succeeded('B')

schedules:
  - cron:
    "35 10 * * *"
    displayName: Agendamento pelo YAML
    branches:
      include:
        - master
    always: true

steps: 
- script: echo "Usando tasks"
  displayName: "Rodar script"
- task: PowerShell@2
  inputs:
    targetType: 'inline'
    script: |
    # Write commands here

    Write-Host "Usando tasks no YAML"
    Write-Host $(variableName)
  - task: PublishBuildArtifact@1
    inputs:
      PathToPublish: '.'
      ArtifactName: 'drop-yaml'
      publishLocation: 'Container'